services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./server/prometheus:/etc/prometheus
  tempo:
    image: grafana/tempo
    container_name: tempo
    command: [ "-config.file=/opt/tempo/tempo.yaml" ]
    volumes:
      - ./server/tempo/tempo.yaml:/opt/tempo/tempo.yaml
    ports:
      - "3200:3200"   # tempo
      - "4318:4318"  # otlp http
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./server/grafana:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
  
