---
alerting:
  alertmanagers:
    - api_version: v1
      scheme: http
      static_configs:
        - targets: []
      timeout: 10s
global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s
scrape_configs:
  - honor_timestamps: true
    job_name: prometheus
    metrics_path: /metrics
    scheme: http
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - localhost:9090
  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]
  - job_name: node
    metrics_path: /metrics
    scheme: http
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - localhost:9100
          - localhost:9101